prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/app_211981_push_notifications_credentials.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/forms.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/logo_company_logo_png.sql
@@application/shared_components/files/css_common_css.sql
@@application/shared_components/files/lolface_jpg.sql
@@application/shared_components/files/bg_jpg.sql
@@application/shared_components/files/misc_blank_user_png.sql
@@application/shared_components/files/app_bg_jpg.sql
@@application/shared_components/files/app_bg2_jpg.sql
@@application/shared_components/files/css_common_min_css.sql
@@application/shared_components/files/emails_image_1_png.sql
@@application/shared_components/files/emails_image_2_png.sql
@@application/shared_components/files/emails_image_3_png.sql
@@application/shared_components/files/emails_image_4_png.sql
@@application/shared_components/files/emails_image_5_png.sql
@@application/shared_components/files/emails_image_6_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/app_username.sql
@@application/shared_components/logic/application_items/app_user_img.sql
@@application/shared_components/logic/application_items/app_user_type.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/client_list.sql
@@application/shared_components/user_interface/lovs/dept_dname.sql
@@application/shared_components/user_interface/lovs/emp_ename.sql
@@application/shared_components/user_interface/lovs/ename.sql
@@application/shared_components/user_interface/lovs/rc_list.sql
@@application/shared_components/user_interface/lovs/user_type_list.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/profile.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/email/templates/pw_reset_link.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/landev_users.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00017.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_09997.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10001.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_landev_db_objects.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
